name: CI

# ワークフローをトリガーするイベントを設定
on:
  # mainブランチに pushされた場合 と pull requestされた場合に に実行
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

  # ワークフローを任意に手動で起動することを許可します
  workflow_dispatch:

# ワークフローに定義するジョブを設定
jobs:
  lint:
    # ジョブ名を設定
    name: Lint

    # ビルドやデプロイを実行するイメージを指定
    runs-on: ubuntu-latest

    # ジョブに定義するステップ（タスク）を設定
    steps:
      # nodeをインストールする場合に指定するコマンド
      - name: Installing node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      # packege.jsonを元に必要なパッケージをインストール
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # Lintチェック
      - name: Run lint
        run: npm run lint

  format:
    # ジョブ名を設定
    name: Format check

    # ビルドやデプロイを実行するイメージを指定
    runs-on: ubuntu-latest

    # ジョブに定義するステップ（タスク）を設定
    steps:
      # nodeをインストールする場合に指定するコマンド
      - name: Installing node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      # packege.jsonを元に必要なパッケージをインストール
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # Formatチェック
      - name: Run format check
        run: npm run format

  format:
    # ジョブ名を設定
    name: Type check

    # ビルドやデプロイを実行するイメージを指定
    runs-on: ubuntu-latest

    # ジョブに定義するステップ（タスク）を設定
    steps:
      # nodeをインストールする場合に指定するコマンド
      - name: Installing node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      # packege.jsonを元に必要なパッケージをインストール
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # Formatチェック
      - name: Run format check
        run: npm run check-types

  build:
    # ジョブ名を設定
    name: Build

    # ビルドやデプロイを実行するイメージを指定
    runs-on: ubuntu-latest

    # ジョブに定義するステップ（タスク）を設定
    steps:
      # nodeをインストールする場合に指定するコマンド
      - name: Installing node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      # packege.jsonを元に必要なパッケージをインストール
      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      # ビルド
      - name: Run build
        run: npm run build
