name: Main

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Check lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run typecheck
        run: npm run typecheck
